# Generated by Django 4.2.7 on 2023-12-27 06:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student_Zone",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("name", models.CharField(max_length=50, null=True)),
                ("passwrod", models.CharField(max_length=10, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="student/images/"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
