# Generated by Django 4.2.7 on 2023-12-27 06:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Student_Zone",
            new_name="Regestration",
        ),
        migrations.RenameField(
            model_name="regestration",
            old_name="passwrod",
            new_name="password",
        ),
    ]
